module: user-service
application: olli-iviet
runtime: python27
version: 1
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- ^node_modules/(.*/)?

handlers:
- url: /assets/css
  static_dir: public/assets/css
  expiration: "10m"

- url: /assets/js
  static_dir: public/assets/js
  expiration: "10m"

- url: /assets/img
  static_dir: public/assets/img
  expiration: "10m"

- url: /api.*
  script: main.app
  secure: always

- url: /
  static_files: public/index.html
  upload: public/index.html

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

- name: PIL
  version: latest

- name: ssl
  version: latest

- name: pycrypto
  version: latest

builtins:
- deferred: on
- remote_api: on
